version: '3.8'

services:
  app:
    image: node:24
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3123:3123"
    restart: always
    command: >
      sh -c "
      npm i -g pnpm &&
      pnpm install &&
      pnpm build &&
      pnpm add serve &&
      npx serve -s dist -l 3123
      "